[phases.setup]
nixPkgs = ["python311", "pip", "postgresql"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "npm install"
]

[phases.build]
cmds = [
  "cd backend && python manage.py migrate",
  "cd backend && python manage.py collectstatic --noinput",
  "npm run build"
]

[start]
cmd = "cd backend && python manage.py runserver 0.0.0.0:$PORT"
