[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python manage.py runserver 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { DJANGO_SETTINGS_MODULE = "ecosystia.settings.production" }
